name: "Build Trunk"

on:
  push:
    branches:
      - trunk

jobs:
  docker-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: docker build -t ghcr.io/${{ github.repository_owner }}/hsr:trunk . && docker push ghcr.io/${{ github.repository_owner }}/hsr:trunk