name: "Development Workflow"

on:
  push:
    branches-ignore:
      - trunk

jobs:
  docker-image:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: docker build -t ghcr.io/${{ github.repository_owner }}/hsr:dev . && docker push ghcr.io/${{ github.repository_owner }}/hsr:dev
      # - name: Logout
      #   run: docker logout kio.ee

  # harbor-scan-report:
  #   name: Harbor Image Scan Report
  #   runs-on: ubuntu-latest
  #   needs: docker-image

  #   steps:
  #     - name: Run Report
  #       uses: kyberorg/harbor-scan-report@22-report-only-fixable
  #       with:
  #         harbor-host: kio.ee
  #         harbor-robot: ${{ secrets.HARBOR_ROBOT }}
  #         harbor-token: ${{ secrets.HARBOR_TOKEN }}
  #         image: kio.ee/hub/library/centos:latest
  #         max-allowed-severity: high
